reverse string
Nikby53/strings pull request #1
Opened 2021-08-02 16:19 UTC by Nikby53

add implementation and test

2021-08-03 06:24 UTC, papahmsolo requested changes
Looks good! Let's improve it a bit.

Can we add a readme file describing the repo?

2021-08-03 06:24 UTC, papahmsolo commented on strings.go
> +package string_utils
- can we get rid of `utils` in the name?
- let's add a package description

2021-08-03 06:24 UTC, papahmsolo commented on strings_test.go
> +	})
- no need for subtests with `t.Run()` as there's only one test
- let's add more test cases. Try non-ascii strings, some corner cases like empty string

2021-08-04 07:01 UTC, papahmsolo requested changes
👀

2021-08-04 07:01 UTC, papahmsolo commented on strings_test.go
> +			}
- let's use `q` in format string, to highlight spaces
- `e.in` will show the input string of the test case instead of reversed value

2021-08-04 10:31 UTC, Nikby53 commented on strings.go
> +package string_utils
done

2021-08-04 10:32 UTC, Nikby53 commented on strings_test.go
> +	})
already done

2021-08-04 10:33 UTC, Nikby53 commented on go.mod
> +go 1.16
ridded

2021-08-04 10:33 UTC, Nikby53 commented on strings_test.go
> +			}
done

2021-08-04 11:46 UTC, alextur approved these changes

2021-08-04 12:12 UTC, merged