count symbols in string
Nikby53/strings pull request #2
Opened 2021-08-02 16:23 UTC by Nikby53

add count implementation and test

2021-08-03 06:45 UTC, papahmsolo requested changes
Cool! Let's also add a go.mod file, it should be committed to the repo.

2021-08-03 06:45 UTC, papahmsolo commented on strings.go
> +}
This works fine. However, string is a slice, so we can get the number of symbols by the length of it. Beware of encoding problems.

2021-08-04 07:04 UTC, papahmsolo requested changes
Can we change the target branch for merging to `main`?

2021-08-04 07:04 UTC, papahmsolo commented on strings_test.go
>  }
Let's add more test cases

2021-08-04 10:35 UTC, Nikby53 commented on strings.go
> +}
Ok, i figured it out

2021-08-04 10:35 UTC, Nikby53 commented on strings_test.go
>  }
added

2021-08-04 14:46 UTC, alextur approved these changes

2021-08-04 15:23 UTC, merged